name: Run Tests & Coverage

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

env:
  PYTHON_VERSION: "3.10"

jobs:
  test:
    name: Run Tests with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run unittests with coverage
        run: poetry run coverage run --source=torchbase -m unittest discover -s tests

      - name: Generate coverage report
        run: poetry run coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: sssohrab/torchbase
          file: coverage.xml
          fail_ci_if_error: true
          flags: unittests

      - name: Enforce minimum coverage threshold (70%)
        run: |
          poetry run coverage report --fail-under=70
